In [3]:
import numpy as np
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([7,8,9,10]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [4]:
a+b

array([[ 8, 10],
       [12, 14]])

In [5]:
b

array([[ 7,  8],
       [ 9, 10]])

In [6]:
b-a

array([[6, 6],
       [6, 6]])

In [7]:
b/a

array([[7. , 4. ],
       [3. , 2.5]])

In [8]:
a*b

array([[ 7, 16],
       [27, 40]])

In [9]:
a.dot(b)

array([[25, 28],
       [57, 64]])

In [10]:
import numpy as np 
arr=np.array([10,20,30,40,50])
o=np.min(arr)
o

10

In [11]:
np.max(arr)

50

In [12]:
np.argmin(arr)                 #returns index number

0

In [13]:
np.argmax(arr)                  #returns index number 

4

In [14]:
np.sqrt(arr)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [15]:
np.sin(arr)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [16]:
np.cos(arr)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [18]:
pushpendra=np.arange(1,11)
np.sqrt(pushpendra)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

# Some more important functions

In [21]:
import numpy as np
a=np.array([10,20,30,40,50])
np.linspace(10,50,5)

array([10., 20., 30., 40., 50.])

In [22]:
np.random.seed(122)
matrix=np.random.randint(1,21,9).reshape(3,3)
matrix

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [23]:
np.sum(matrix)

116

In [24]:
matrix.sum()

116

In [25]:
np.min(matrix,axis=1)      #finds rows wise min

array([11, 13,  3])

In [26]:
np.max(matrix,axis=0)   #finds columns wise max

array([17, 16, 16])

In [27]:
np.cumsum(matrix)    #cumulative sum or jis prakar sanchayi barambarata hoti hai.

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116])

In [28]:
np.cumsum(matrix,axis=0)

array([[16, 11, 13],
       [33, 24, 29],
       [36, 40, 40]])

In [34]:
import numpy as np
np.random.seed(122)
arr=np.random.randint(1,21,10)
arr


array([16, 11, 13, 17, 13, 16,  3, 16, 11, 10])

In [36]:
np.unique(arr)

array([ 3, 10, 11, 13, 16, 17])

In [37]:
np.unique(arr).size

6

In [38]:
np.unique(arr,return_index=True,return_counts=True)

(array([ 3, 10, 11, 13, 16, 17]),
 array([6, 9, 1, 2, 0, 3], dtype=int64),
 array([1, 1, 2, 2, 3, 1], dtype=int64))